cookie:
  expiry_days: 10
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    user5a:
      email: aramarx.us@gmail.com 
      name: User Five A
      password: cheatham5a1
preauthorized:
  emails: aramarx.us@gmail.com
